development:
  adapter: postgresql
  encoding: unicode
  database: comrade_tweet_development
  pool: 5
  username: wei
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: comrade_tweet_test
  pool: 5
  username: wei
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: comrade_tweet_production
  pool: 5
  username: wei
  password:
